### ISSUE TITLE
Please help me install MACOS Hackintosh on my laptop HP Probook 650 G1

### ISSUE THREAD

**Issue by at-tantv** [ammoune78/Desktop-DSDT-SSDT-Patches#1]
My laptop profile:
HP Probook 650 G1
CPU | Intel Core i5 4200M 2.5GHz (Turbo Speed : 3.1 GHz)
RAM | DDR3 8GB, 2 Slot
VGA | HD 4600
HDD | 1 SSD 128GB, 1 HDD 320 GB 7200 rpm
Screen | 15,6 inch Full HD 1920 x 1080

Can I install MacOS 10.13 High Serria or 10.14 Mojave?
Could you send link tutorial or guide or EFI Folder for me ?

**Comment by ammoune78** [comment]
Hello, i away years now, and didn't checked your comment. As answer for your request, you need to check for possible help in tonymacx86 website, and see post for your laptop because rehabman made a guide  especially for those laptops from hp with all things needed.
Because of no issue, i'll close it
